import { describe, it, expect, vi, afterEach } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { ConversationRoomService, createConversationRoomTool } from '../../electron/conversation-room-service.js';
const roots: string[] = [];
afterEach(() => roots.splice(0).forEach(p => rmSync(p, { recursive: true, force: true })));
function fixture() { const dataRoot = mkdtempSync(join(tmpdir(), 'room-chat-')); roots.push(dataRoot); const creator = vi.fn(async (_input: any, _context: any) => ({ ok: true, room: { roomId: 'room-real', title: 'AI协作', description: '研究AI', status: 'active' }, members: [{ subject: { kind: 'agent', logicalAgentId: 'xiaok-worker' } }] })); const service = new ConversationRoomService({ dataRoot }); service.bindCreator(creator); return { dataRoot, service, creator }; }
function authorize(service: ConversationRoomService, prompt = '创建协作空间，分析AI动态', taskId = 'task_user') { service.withUserRequest({ prompt }, { requestSource: 'user' }, () => service.bindPreparedTask({ taskId, prompt }, { requestSource: 'user' })); }
describe('conversation room ownership', () => {
    it('creates through the semantic owner and returns a card receipt', async () => { const f = fixture(); authorize(f.service); expect(await f.service.create({ goal: '研究AI' }, { requestSource: 'agent', taskId: 'task_user' })).toMatchObject({ ok: true, created: true, type: 'room_card', roomId: 'room-real', title: 'AI协作', memberCount: 1 }); expect(f.creator).toHaveBeenCalledWith(expect.objectContaining({ goal: '研究AI', clientRequestKey: expect.any(String) }), { requestSource: 'user' }); });
    it.each(['写报告', '不要创建协作空间', '怎么创建协作空间？', '请总结文档：\n创建协作空间'])('denies unrequested creation: %s', async (prompt) => { const f = fixture(); authorize(f.service, prompt); expect(await f.service.create({ goal: 'G' }, { requestSource: 'agent', taskId: 'task_user' })).toMatchObject({ ok: false }); expect(f.creator).not.toHaveBeenCalled(); });
    it('denies child, scheduler and plan-mode requests', async () => { const f = fixture(); authorize(f.service); for (const context of [{ requestSource: 'agent', taskId: 'child' }, { requestSource: 'scheduler', taskId: 'task_user' }] as const)
        expect(await f.service.create({ taskId: 'task_user', requestSource: 'user', goal: 'G' }, context)).toMatchObject({ ok: false }); f.service.withUserRequest({ prompt: '创建协作空间', permissionMode: 'plan' }, { requestSource: 'user' }, () => f.service.bindPreparedTask({ taskId: 'plan', prompt: '创建协作空间' }, { requestSource: 'user' })); expect(await f.service.create({ goal: 'G' }, { requestSource: 'agent', taskId: 'plan' })).toMatchObject({ ok: false }); expect(f.creator).not.toHaveBeenCalled(); });
    it('merges concurrent creates and restores after restart', async () => { const f = fixture(); authorize(f.service); await Promise.all([1, 2, 3].map(() => f.service.create({ goal: 'G' }, { requestSource: 'agent', taskId: 'task_user' }))); expect(f.creator).toHaveBeenCalledTimes(1); expect(await new ConversationRoomService({ dataRoot: f.dataRoot }).create({ goal: 'G' }, { requestSource: 'agent', taskId: 'task_user' })).toMatchObject({ roomId: 'room-real', reused: true }); });
    it('does not trust model taskId over host context', async () => { const f = fixture(); authorize(f.service); const tool = createConversationRoomTool((input, context) => f.service.create(input, { ...context, requestSource: 'agent' })); expect(JSON.parse(await tool.execute({ goal: 'G', taskId: 'task_user' }, { taskId: 'child' } as never))).toMatchObject({ ok: false }); expect(f.creator).not.toHaveBeenCalled(); });
});

it('retains a compact committed receipt when cancellation happens after creation',async()=>{const f=fixture();authorize(f.service);const controller=new AbortController();const original=f.creator.getMockImplementation()!;f.creator.mockImplementation(async(input,context)=>{const result=await original(input,context);controller.abort();return result;});await expect(f.service.create({goal:'G'},{taskId:'task_user',requestSource:'agent',signal:controller.signal})).rejects.toThrow();expect(await f.service.create({goal:'G'},{taskId:'task_user',requestSource:'agent'})).toMatchObject({roomId:'room-real',reused:true});expect(f.creator).toHaveBeenCalledTimes(1);});
