import {changedFiles} from '../../scripts/governance/check.mjs';
import {execFileSync} from 'node:child_process';
import {renameSync, readFileSync} from 'node:fs';
import { test, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { checkArchitecture } from '../../scripts/governance/architecture.mjs';
import { checkLint } from '../../scripts/governance/lint.mjs';
import { makeBaseline, compareBaseline } from '../../scripts/governance/baseline.mjs';
const roots = [];
afterEach(() => { for (const p of roots.splice(0))
    rmSync(p, { recursive: true, force: true }); });
function fixture() { const root = mkdtempSync(join(tmpdir(), 'xiaok-governance-')); roots.push(root); for (const path of policy.roots) mkdirSync(join(root, path), {recursive:true}); return root; }
function put(root, path, text) { mkdirSync(dirname(join(root, path)), { recursive: true }); writeFileSync(join(root, path), text); }
const policy = { version: 1, roots: ['desktop/electron', 'desktop/renderer/src', 'desktop/shared', 'src'], preload: ['desktop/electron/preload.cjs', 'desktop/electron/preload-api.ts'], publicTypeContracts: ['desktop/electron/preload-api.ts'], aliases: { '@/*': ['desktop/renderer/src/*'] } };
test('real AST rejects import/re-export/require/dynamic aliases, permits type public contract', () => { const root = fixture(); put(root, 'desktop/electron/private.ts', 'export const secret=1;'); put(root, 'desktop/electron/preload-api.ts', 'export interface API {x:number}'); put(root, 'desktop/renderer/src/a.ts', "import type {API} from '../../electron/preload-api.js'; export {secret} from '../../electron/private.js'; const fs=require('node:fs'); import('electron'); import(variable);"); const r = checkArchitecture({ root, policy }); assert.equal(r.newDiagnostics.length, 4); assert.ok(r.newDiagnostics.some(d => d.rule === 'dynamic-import')); });
test('shared barrel runtime escape is caught and changed includes indirect reverse importers', () => { const root = fixture(); put(root, 'desktop/electron/private.ts', 'export const secret=1;'); put(root, 'desktop/shared/barrel.ts', "export {secret} from '../electron/private.js';"); put(root, 'desktop/renderer/src/mid.ts', "export {secret} from '../../shared/barrel.js';"); put(root, 'desktop/renderer/src/app.ts', "import {secret} from '@/mid'; console.log(secret);"); const r = checkArchitecture({ root, policy, changedFiles: ['desktop/electron/private.ts'] }); assert.ok(r.checkedFiles.includes('desktop/renderer/src/app.ts')); assert.ok(r.newDiagnostics.some(d => d.rule === 'host-through-shared')); });
test('deleted target retains reverse importer and reports unresolved code import', () => { const root = fixture(); put(root, 'desktop/renderer/src/app.ts', "import {x} from './deleted.js'; console.log(x);"); const r = checkArchitecture({ root, policy, changedFiles: ['desktop/renderer/src/deleted.ts'] }); assert.ok(r.checkedFiles.includes('desktop/renderer/src/app.ts')); assert.ok(r.newDiagnostics.some(d => d.rule === 'unresolved-import')); });
test('baseline permits the exact old violation, rejects extra duplicate and replacement', () => { const old = { path: 'a.ts', rule: 'unsafe', source: 'debugger;', message: 'bad' }; const b = makeBaseline([old]); assert.equal(compareBaseline([old], b).length, 0); assert.equal(compareBaseline([old, old], b).length, 1); assert.equal(compareBaseline([{ ...old, source: 'eval(code);' }], b).length, 1); });
test('actual Oxlint catches new code even when total violation count does not grow', () => { const root = fixture(); put(root, 'src/a.ts', 'function oldProblem(){ debugger; }\noldProblem();'); let r = checkLint({ root, paths: ['src'] }); assert.ok(r.newDiagnostics.length > 0); const baseline = makeBaseline(r.diagnostics, r.metadata); assert.equal(checkLint({ root, paths: ['src'], baseline }).newDiagnostics.length, 0); put(root, 'src/a.ts', 'function newProblem(){ debugger; }\nnewProblem();'); r = checkLint({ root, paths: ['src'], baseline }); assert.ok(r.newDiagnostics.length > 0); });
test('parser errors and bad baseline configuration fail rather than being grandfathered', () => { const root = fixture(); put(root, 'src/a.ts', 'const = ;'); assert.throws(() => checkLint({ root, paths: ['src'] }), /parse|syntax/i); put(root, 'src/a.ts', 'const a=1; console.log(a);'); const r = checkLint({ root, paths: ['src'] }); assert.throws(() => checkLint({ root, paths: ['src'], baseline: makeBaseline([], { ...r.metadata, configHash: 'wrong' }) }), /baseline|configuration/i); });
test('preload external packages and main reverse shared-barrel imports are forbidden', () => { const root = fixture(); put(root, 'desktop/renderer/src/ui.ts', 'export const ui=1;'); put(root, 'desktop/shared/barrel.ts', "export {ui} from '../renderer/src/ui.js';"); put(root, 'desktop/electron/main.ts', "import {ui} from '../shared/barrel.js';"); put(root, 'desktop/electron/preload.cjs', "const electron=require('electron');require('better-sqlite3');"); const r = checkArchitecture({ root, policy }); assert.ok(r.newDiagnostics.some(d => d.rule === 'preload-host-runtime')); assert.ok(r.newDiagnostics.some(d => d.rule === 'renderer-through-shared')); });

test('actual Git changed discovery includes both sides of a rename',()=>{const root=fixture();const git=(...args)=>execFileSync('git',['-C',root,...args],{stdio:'pipe'});git('init');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');put(root,'desktop/renderer/src/old.ts','export const value=1;');git('add','.');git('commit','-m','baseline');renameSync(join(root,'desktop/renderer/src/old.ts'),join(root,'desktop/renderer/src/new.ts'));git('add','.');const files=changedFiles('HEAD',root);assert.ok(files.includes('desktop/renderer/src/old.ts'));assert.ok(files.includes('desktop/renderer/src/new.ts'));});
test('valid JSX remains parseable while forbidden host imports are rejected',()=>{const root=fixture();put(root,'desktop/renderer/src/app.jsx',"import fs from 'node:fs'; export const UI=()=> <div>ok</div>;");const r=checkArchitecture({root,policy});assert.equal(r.newDiagnostics.length,1);});
test('a missing architecture source root fails instead of silently shrinking scope',()=>{const root=fixture();put(root,'src/active.ts','export const active=true;');rmSync(join(root,'desktop/renderer/src'),{recursive:true});assert.throws(()=>checkArchitecture({root,policy}),/missing architecture source root/i);});
test('lint configuration bytes survive a real Git CRLF checkout',()=>{const root=fixture();const git=(...args)=>execFileSync('git',['-C',root,...args],{stdio:'pipe'});const config=readFileSync(new URL('../../.oxlintrc.json',import.meta.url));put(root,'.oxlintrc.json',config);put(root,'.gitattributes',readFileSync(new URL('../../.gitattributes',import.meta.url)));git('init');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('add','.');git('commit','-m','config');const checkout=join(fixture(),'checkout');git('-c','core.autocrlf=true','clone','--quiet',root,checkout);assert.deepEqual(readFileSync(join(checkout,'.oxlintrc.json')),config);});
